//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooBuzyClient.TooBuzyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TooBuzyServiceReference.ITooBuzyService")]
    public interface ITooBuzyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/CreateConsumer", ReplyAction="http://tempuri.org/ITooBuzyService/CreateConsumerResponse")]
        void CreateConsumer(TooBuzyEntities.Consumer consumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/CreateConsumer", ReplyAction="http://tempuri.org/ITooBuzyService/CreateConsumerResponse")]
        System.Threading.Tasks.Task CreateConsumerAsync(TooBuzyEntities.Consumer consumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/GetConsumerById", ReplyAction="http://tempuri.org/ITooBuzyService/GetConsumerByIdResponse")]
        TooBuzyEntities.Consumer GetConsumerById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/GetConsumerById", ReplyAction="http://tempuri.org/ITooBuzyService/GetConsumerByIdResponse")]
        System.Threading.Tasks.Task<TooBuzyEntities.Consumer> GetConsumerByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/GetAll", ReplyAction="http://tempuri.org/ITooBuzyService/GetAllResponse")]
        TooBuzyEntities.Consumer[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/GetAll", ReplyAction="http://tempuri.org/ITooBuzyService/GetAllResponse")]
        System.Threading.Tasks.Task<TooBuzyEntities.Consumer[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/UpdateConsumer", ReplyAction="http://tempuri.org/ITooBuzyService/UpdateConsumerResponse")]
        void UpdateConsumer(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/UpdateConsumer", ReplyAction="http://tempuri.org/ITooBuzyService/UpdateConsumerResponse")]
        System.Threading.Tasks.Task UpdateConsumerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/DeleteConsumer", ReplyAction="http://tempuri.org/ITooBuzyService/DeleteConsumerResponse")]
        void DeleteConsumer(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/DeleteConsumer", ReplyAction="http://tempuri.org/ITooBuzyService/DeleteConsumerResponse")]
        System.Threading.Tasks.Task DeleteConsumerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/GetByInt", ReplyAction="http://tempuri.org/ITooBuzyService/GetByIntResponse")]
        TooBuzyEntities.Consumer GetByInt(int phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITooBuzyService/GetByInt", ReplyAction="http://tempuri.org/ITooBuzyService/GetByIntResponse")]
        System.Threading.Tasks.Task<TooBuzyEntities.Consumer> GetByIntAsync(int phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITooBuzyServiceChannel : TooBuzyClient.TooBuzyServiceReference.ITooBuzyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TooBuzyServiceClient : System.ServiceModel.ClientBase<TooBuzyClient.TooBuzyServiceReference.ITooBuzyService>, TooBuzyClient.TooBuzyServiceReference.ITooBuzyService {
        
        public TooBuzyServiceClient() {
        }
        
        public TooBuzyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TooBuzyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TooBuzyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TooBuzyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateConsumer(TooBuzyEntities.Consumer consumer) {
            base.Channel.CreateConsumer(consumer);
        }
        
        public System.Threading.Tasks.Task CreateConsumerAsync(TooBuzyEntities.Consumer consumer) {
            return base.Channel.CreateConsumerAsync(consumer);
        }
        
        public TooBuzyEntities.Consumer GetConsumerById(int Id) {
            return base.Channel.GetConsumerById(Id);
        }
        
        public System.Threading.Tasks.Task<TooBuzyEntities.Consumer> GetConsumerByIdAsync(int Id) {
            return base.Channel.GetConsumerByIdAsync(Id);
        }
        
        public TooBuzyEntities.Consumer[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TooBuzyEntities.Consumer[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void UpdateConsumer(int Id) {
            base.Channel.UpdateConsumer(Id);
        }
        
        public System.Threading.Tasks.Task UpdateConsumerAsync(int Id) {
            return base.Channel.UpdateConsumerAsync(Id);
        }
        
        public void DeleteConsumer(int Id) {
            base.Channel.DeleteConsumer(Id);
        }
        
        public System.Threading.Tasks.Task DeleteConsumerAsync(int Id) {
            return base.Channel.DeleteConsumerAsync(Id);
        }
        
        public TooBuzyEntities.Consumer GetByInt(int phone) {
            return base.Channel.GetByInt(phone);
        }
        
        public System.Threading.Tasks.Task<TooBuzyEntities.Consumer> GetByIntAsync(int phone) {
            return base.Channel.GetByIntAsync(phone);
        }
    }
}
